parameters: {}
environment: {}
packages:
    - name: polymarket
      shared: false
      environment:
        MONGO_URI: ${DATABASE_URL}
        MONGO_DB: "polymarket"
      parameters: {}
      annotations: {}
      functions:
        - name: markets
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: {}
          environment: 
            MONGO_COLLECTION: "markets"
          annotations: {}
          limits: 
            timeout: 100000
          triggers:
          - name: trigger-markets
            sourceType: scheduler
            sourceDetails:
              cron: "*/5 * * * *"
